In [13]:
import numpy as np

# Load the data from the file
data = np.loadtxt('dist.txt')

#conver to int
data = data.astype(int)

In [14]:
tij = np.zeros((115, 115))

for n in range(len(data)):
    i = data[n][0] - 1
    j = data[n][1] - 1
    tij[i][j] = data[n][2]
    tij[j][i] = data[n][2]

print(tij)

[[ 0. 14.  7. ... 20. 20. 19.]
 [14.  0. 11. ...  9.  8.  8.]
 [ 7. 11.  0. ... 18. 18. 17.]
 ...
 [20.  9. 18. ...  0.  2.  2.]
 [20.  8. 18. ...  2.  0.  1.]
 [19.  8. 17. ...  2.  1.  0.]]


In [15]:
import pandas as pd

df = pd.read_csv('tasks.csv', header=0, sep=';')

t = np.zeros((725, 725))

for i in range(len(df)):
    finish = df['ZastavkaFinish'][i]
    for j in range(len(df)):
        start = df['ZastavkaStart'][j]
        t[i][j] = tij[finish][start]

print(t)


[[ 0.  9.  2. ... 17. 17.  0.]
 [ 7.  3.  9. ... 11. 11.  7.]
 [17.  8. 19. ...  0.  0. 17.]
 ...
 [ 2. 11.  0. ... 19. 19.  2.]
 [ 2. 11.  0. ... 19. 19.  2.]
 [ 0.  9.  2. ... 17. 17.  0.]]


In [11]:
import pandas as pd

df = pd.read_csv('../turnus/data/praha/tasks.csv', header=0, sep=';')

df.sort_values(by=['CasStart'], inplace=True)

df['Index'] = [i for i in range(0, len(df))]

df.to_csv('tasks.csv', sep=';', index=False)

In [16]:
np.savetxt('output.txt', t, delimiter=';', fmt='%i')

In [31]:
df['CasFinish'][543], df['CasStart'][617]

(469, 350)

In [32]:
t[543][617]

9.0